# Generated by Django 5.2.15 on 2026-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('experience_level', models.CharField(max_length=50)),
                ('years_of_experience', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('responsibilities', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
