# Generated by Django 5.2.15 on 2026-06-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='gemini_feedback',
            field=models.TextField(blank=True),
        ),
    ]
